export const productsArray = [
  // 🍔 Burgers (8)
  {
    id: 1,
    name: "Classic Burger",
    image: "./StovaBilder/purple-burger-transparent.jpg",
    price: 129,
    category: "Burger",
  },
  {
    id: 2,
    name: "Cheeseburger Deluxe",
    image: "./StovaBilder/burger1-transparent.jpg",
    price: 139,
    category: "Burger",
  },
  {
    id: 3,
    name: "Bacon BBQ Burger",
    image: "./StovaBilder/burger2-transparent.jpg",
    price: 149,
    category: "Burger",
  },
  {
    id: 4,
    name: "Vegan Burger",
    image: "./StovaBilder/burger3-transparent.jpg",
    price: 135,
    category: "Burger",
  },
  {
    id: 5,
    name: "Double Smash Burger",
    image: "./StovaBilder/burger4-transparent.jpg",
    price: 159,
    category: "Burger",
  },
  {
    id: 6,
    name: "Truffle Burger",
    image: "./StovaBilder/burger5-transparent.jpg",
    price: 169,
    category: "Burger",
  },
  {
    id: 7,
    name: "Blue Cheese Burger",
    image: "./StovaBilder/burger6-transparent.jpg",
    price: 155,
    category: "Burger",
  },
  {
    id: 8,
    name: "Jalapeño Burger",
    image: "./StovaBilder/burger7-transparent.jpg",
    price: 145,
    category: "Burger",
  },

  // 🌭 Sausages (8)
  {
    id: 9,
    name: "Classic Grilled Sausage",
    image: "./StovaBilder/sausage1-transparent.jpg",
    price: 59,
    category: "Pølse",
  },
  {
    id: 10,
    name: "Cheese Sausage",
    image: "./StovaBilder/sausage2-transparent.jpg",
    price: 65,
    category: "Pølse",
  },
  {
    id: 11,
    name: "Chili Sausage",
    image: "./StovaBilder/sausage3-transparent.jpg",
    price: 69,
    category: "Pølse",
  },
  {
    id: 12,
    name: "Bacon Sausage",
    image: "./StovaBilder/sausage4-transparent.jpg",
    price: 72,
    category: "Pølse",
  },
  {
    id: 13,
    name: "Vegan Sausage",
    image: "./StovaBilder/sausage5-transparent.jpg",
    price: 65,
    category: "Pølse",
  },
  {
    id: 14,
    name: "Lamb Sausage",
    image: "./StovaBilder/sausage6-transparent.jpg",
    price: 75,
    category: "Pølse",
  },
  {
    id: 15,
    name: "Bratwurst",
    image: "./StovaBilder/sausage7-transparent.jpg",
    price: 80,
    category: "Pølse",
  },
  {
    id: 16,
    name: "Currywurst",
    image: "./StovaBilder/sausage8-transparent.jpg",
    price: 85,
    category: "Pølse",
  },

  // 🥤 Drinks (8)
  {
    id: 17,
    name: "Cola",
    image: "./StovaBilder/cola-transparent.jpg",
    price: 39,
    category: "Drikkevare",
  },
  {
    id: 18,
    name: "Cola Zero",
    image: "./StovaBilder/colazero-transparent.jpg",
    price: 39,
    category: "Drikkevare",
  },
  {
    id: 19,
    name: "Orange Soda",
    image: "./StovaBilder/orangeSoda-transparent.jpg",
    price: 35,
    category: "Drikkevare",
  },
  {
    id: 20,
    name: "Sparkling Water",
    image: "./StovaBilder/sparklingwater-transparent.jpg",
    price: 32,
    category: "Drikkevare",
  },
  {
    id: 21,
    name: "Apple Juice",
    image: "./StovaBilder/orangejuice-transparent.jpg",
    price: 30,
    category: "Drikkevare",
  },
  {
    id: 22,
    name: "Chocolate Milkshake",
    image: "./StovaBilder/chocolateMilkshake-transparent.jpg",
    price: 55,
    category: "Drikkevare",
  },
  {
    id: 23,
    name: "Strawberry Milkshake",
    image: "./StovaBilder/strawberryMilkshake-transparent.jpg",
    price: 55,
    category: "Drikkevare",
  },
  {
    id: 24,
    name: "Vanilla Milkshake",
    image: "./StovaBilder/vanillaMilkshake-transparent.jpg",
    price: 55,
    category: "Drikkevare",
  },
];
